spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: smlr
        use_sql_comments: true
        format_sql: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smlr?currentSchema=smlr
    username: smlr
    password: smlr

  liquibase:
    enabled: true
    change-log: classpath:db-changelog.xml

smlr.prefix: http://localhost:8080/
